language: python
sudo: required
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
before_install:
    - "wget https://s3.amazonaws.com/textblob/nltk_data-0.11.0.tar.gz"
    - "tar -xzvf nltk_data-0.11.0.tar.gz -C ~"
# Install dependencies
install:
    - "pip install numpy"
    - "pip install -U ."
    - if [[ $TRAVIS_PYTHON_VERSION == '3.4' ]]; then pip install -r docs/requirements.txt; fi
    - "curl -sSf https://gitlinks.github.io/cl-bins/install.sh | sh"
before_install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libc6; fi
# Run tests
script:
    # Run doctests against py34
    - if [[ $TRAVIS_PYTHON_VERSION == '3.4' ]]; then cd docs && make doctest; fi
    - /home/travis/.gitlinks/hermes-rust-ci
